

CREATE STAGE VITECH_DEV_DB.STAGES.EMPL_STAGE
   URL='s3://snowflake-assignments-mc/copyoptions/example1'

list @VITECH_DEV_DB.STAGES.EMPL_STAGE

--- file formate---
CREATE OR REPLACE FILE FORMAT my_csv_format
  TYPE = 'CSV'
  SKIP_HEADER = 1; 

-----infer schema -----

SELECT *
FROM TABLE(
  INFER_SCHEMA(
    LOCATION => '@VITECH_DEV_DB.STAGES.EMPL_STAGE',
    FILE_FORMAT => 'my_csv_format' 
  )
);

SELECT COUNT(*) AS TOTAL_EMPLOYEES
FROM @VITECH_DEV_DB.STAGES.EMPL_STAGE
(FILE_FORMAT => 'my_csv_format');

CREATE OR REPLACE TABLE VITECH_DEV_DB.PUBLIC.EMPLOYEES (
    C1 VARCHAR,
    C2 VARCHAR,
    C3 VARCHAR,
    C4 VARCHAR,
    C5 NUMBER(2, 0),
    C6 VARCHAR
);

COPY INTO VITECH_DEV_DB.PUBLIC.EMPLOYEES
FROM @VITECH_DEV_DB.STAGES.EMPL_STAGE
FILE_FORMAT = (FORMAT_NAME = 'my_csv_format');

select * from  VITECH_DEV_DB.PUBLIC.EMPLOYEES

count :  122 records
